
package ru.demo.sakai.soap.bindings;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SakaiI18n", targetNamespace = "http://webservices.sakaiproject.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SakaiI18N {


    /**
     * 
     * @param resourceclass
     * @param locale
     * @param resourcebundle
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getI18nProperties")
    @WebResult(partName = "return")
    public String getI18NProperties(
        @WebParam(name = "locale", partName = "locale")
        String locale,
        @WebParam(name = "resourceclass", partName = "resourceclass")
        String resourceclass,
        @WebParam(name = "resourcebundle", partName = "resourcebundle")
        String resourcebundle);

}
